name: firebase_helper
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^2.4.4

  # firebase
  firebase_core: ^3.6.0
  firebase_core_web: ^2.18.1
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.4
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3
  cloud_firestore: ^5.4.4
  cloud_functions: ^5.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono:

  build_runner: ^2.4.13
  
flutter:
