name: hackathon_template
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  fvm: ^3.2.1
  intl: ^0.18.0
  melos: ^6.0.0
  pedantic_mono: ^1.29.0

flutter:
  uses-material-design: true
  # assets:
    # fonts:
