// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkOCsgMLYvJgR20fzLD_g1ZPuP6X_S8BI',
    appId: '1:194581681788:web:90829c1d5f164cb6dcdbf9',
    messagingSenderId: '194581681788',
    projectId: 'flutter-hackthon-2024',
    authDomain: 'flutter-hackthon-2024.firebaseapp.com',
    storageBucket: 'flutter-hackthon-2024.firebasestorage.app',
    measurementId: 'G-KKQJHP6VM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR-9qw74i8GBJpwyP8i4xEVsSuuWKLKpI',
    appId: '1:194581681788:android:fc36f2e250b0bd56dcdbf9',
    messagingSenderId: '194581681788',
    projectId: 'flutter-hackthon-2024',
    storageBucket: 'flutter-hackthon-2024.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWQxPl-lHKEx_ZLw70BNZfL6ItJg_Bk94',
    appId: '1:194581681788:ios:9a095e8ff8a61b09dcdbf9',
    messagingSenderId: '194581681788',
    projectId: 'flutter-hackthon-2024',
    storageBucket: 'flutter-hackthon-2024.firebasestorage.app',
    iosBundleId: 'net.andai.flutterTokyoHackathon2024',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWQxPl-lHKEx_ZLw70BNZfL6ItJg_Bk94',
    appId: '1:194581681788:ios:9a095e8ff8a61b09dcdbf9',
    messagingSenderId: '194581681788',
    projectId: 'flutter-hackthon-2024',
    storageBucket: 'flutter-hackthon-2024.firebasestorage.app',
    iosBundleId: 'net.andai.flutterTokyoHackathon2024',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkOCsgMLYvJgR20fzLD_g1ZPuP6X_S8BI',
    appId: '1:194581681788:web:057098819bf6a9b9dcdbf9',
    messagingSenderId: '194581681788',
    projectId: 'flutter-hackthon-2024',
    authDomain: 'flutter-hackthon-2024.firebaseapp.com',
    storageBucket: 'flutter-hackthon-2024.firebasestorage.app',
    measurementId: 'G-Y2DWG154Y1',
  );
}
