name: flutter_tokyo_hackathon2024
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  helper:
    path: ../../packages/helper
  
  envied: ^0.5.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13

  pedantic_mono: ^1.29.0

  flutter_gen_runner:

flutter:
  generate: false
  uses-material-design: true
  assets:
    - assets/json/

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true
    lottie: true
